### PR TITLE
Fix bad copy paste

### PR DESCRIPTION
**Pull request by kaspernissen**
Not sure what went wrong here. 

I deleted the release, and will make a new release once this is merged.

### CODE REVIEW

**Comment by Crevil** [comment]
Why do you need this? This should not be neccesary?

**Comment by kaspernissen** [comment]
I may have missed how the CI works. It looks like we build the binary in another place, and copy it over. Then it should just be?:
```
FROM golang:1.16.0 as builder
FROM scratch
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT [ "/release-manager-bot" ]

COPY release-manager-bot /
```

**Comment by kaspernissen** [comment]
@Crevil how about now? 🙈

**Review by Crevil — APPROVED** [review]
Should work. You can test it locally with something like this.

```
go build .
docker build -g release-manager-bot-goreleaser -f Dockerfile-goreleaser .
docker run --rm -it release-manager-bot-goreleaser
```

**Pull request merged**
